// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../src/app/(dashboard)/admin/alerts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/alerts">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/admin/alerts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/admin/approvals/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/approvals">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/admin/approvals/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/admin/data-tools/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/data-tools">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/admin/data-tools/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/admin/escrow/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/escrow">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/admin/escrow/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/admin/financials/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/financials">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/admin/financials/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/admin/payouts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/payouts">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/admin/payouts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/admin/posts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/posts">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/admin/posts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/admin/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/reports">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/admin/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/admin/reviews/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/reviews">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/admin/reviews/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/admin/sessions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/sessions">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/admin/sessions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/admin/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/settings">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/admin/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/admin/slider/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/slider">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/admin/slider/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/admin/supervisors/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/supervisors">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/admin/supervisors/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/admin/teacher-pricing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/teacher-pricing">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/admin/teacher-pricing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/admin/tracks/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/tracks">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/admin/tracks/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/admin/transactions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/transactions">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/admin/transactions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/admin/trials/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/trials">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/admin/trials/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/admin/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/users">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/admin/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/admin/whatsapp-reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/whatsapp-reports">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/admin/whatsapp-reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/parent/calendar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/parent/calendar">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/parent/calendar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/parent/gamification/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/parent/gamification">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/parent/gamification/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/parent/homework/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/parent/homework">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/parent/homework/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/parent/leaderboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/parent/leaderboard">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/parent/leaderboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/parent/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/parent">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/parent/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/parent/payments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/parent/payments">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/parent/payments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/parent/recommendations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/parent/recommendations">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/parent/recommendations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/parent/refunds/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/parent/refunds">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/parent/refunds/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/parent/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/parent/reports">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/parent/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/parent/sessions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/parent/sessions">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/parent/sessions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/parent/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/parent/settings">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/parent/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/parent/students/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/parent/students">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/parent/students/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/supervisor/finances/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/supervisor/finances">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/supervisor/finances/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/supervisor/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/supervisor">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/supervisor/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/supervisor/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/supervisor/profile">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/supervisor/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/supervisor/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/supervisor/reports">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/supervisor/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/supervisor/sessions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/supervisor/sessions">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/supervisor/sessions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/teacher/courses/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/teacher/courses">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/teacher/courses/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/teacher/homework/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/teacher/homework">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/teacher/homework/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/teacher/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/teacher">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/teacher/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/teacher/payouts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/teacher/payouts">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/teacher/payouts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/teacher/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/teacher/profile">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/teacher/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/teacher/reviews/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/teacher/reviews">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/teacher/reviews/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/teacher/schedule/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/teacher/schedule">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/teacher/schedule/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/(dashboard)/teacher/students/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/teacher/students">> = Specific
  const handler = {} as typeof import("../../../src/app/(dashboard)/teacher/students/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/auth/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/login">> = Specific
  const handler = {} as typeof import("../../../src/app/auth/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/auth/register/student/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/register/student">> = Specific
  const handler = {} as typeof import("../../../src/app/auth/register/student/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/auth/register/teacher/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/register/teacher">> = Specific
  const handler = {} as typeof import("../../../src/app/auth/register/teacher/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/checkout/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/checkout">> = Specific
  const handler = {} as typeof import("../../../src/app/checkout/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/classroom/[sessionId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/classroom/[sessionId]">> = Specific
  const handler = {} as typeof import("../../../src/app/classroom/[sessionId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/classroom/sandbox/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/classroom/sandbox">> = Specific
  const handler = {} as typeof import("../../../src/app/classroom/sandbox/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/payment/cancel/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/payment/cancel">> = Specific
  const handler = {} as typeof import("../../../src/app/payment/cancel/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/payment/sandbox/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/payment/sandbox">> = Specific
  const handler = {} as typeof import("../../../src/app/payment/sandbox/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/payment/success/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/payment/success">> = Specific
  const handler = {} as typeof import("../../../src/app/payment/success/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/privacy-policy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy-policy">> = Specific
  const handler = {} as typeof import("../../../src/app/privacy-policy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms">> = Specific
  const handler = {} as typeof import("../../../src/app/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/ably/auth/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ably/auth">> = Specific
  const handler = {} as typeof import("../../../src/app/api/ably/auth/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/backup/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/backup">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/backup/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/export/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/export">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/export/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/posts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/posts">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/posts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/reset/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/reset">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/reset/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/session-media/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/session-media">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/session-media/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/settings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/settings">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/settings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/slider/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/slider">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/slider/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/supervisor-payouts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/supervisor-payouts">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/supervisor-payouts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/supervisors/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/supervisors">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/supervisors/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/admin/tracks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/tracks">> = Specific
  const handler = {} as typeof import("../../../src/app/api/admin/tracks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/delete-account/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/delete-account">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/delete-account/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/login">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/logout">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/me/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/me">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/me/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/auth/register/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/register">> = Specific
  const handler = {} as typeof import("../../../src/app/api/auth/register/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/classroom/chat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/classroom/chat">> = Specific
  const handler = {} as typeof import("../../../src/app/api/classroom/chat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/classroom/focus/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/classroom/focus">> = Specific
  const handler = {} as typeof import("../../../src/app/api/classroom/focus/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/classroom/game-points/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/classroom/game-points">> = Specific
  const handler = {} as typeof import("../../../src/app/api/classroom/game-points/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/classroom/join/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/classroom/join">> = Specific
  const handler = {} as typeof import("../../../src/app/api/classroom/join/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/classroom/lesson/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/classroom/lesson">> = Specific
  const handler = {} as typeof import("../../../src/app/api/classroom/lesson/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/classroom/log/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/classroom/log">> = Specific
  const handler = {} as typeof import("../../../src/app/api/classroom/log/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/classroom/recording/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/classroom/recording">> = Specific
  const handler = {} as typeof import("../../../src/app/api/classroom/recording/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/classroom/whiteboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/classroom/whiteboard">> = Specific
  const handler = {} as typeof import("../../../src/app/api/classroom/whiteboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/dashboard/admin/alerts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/admin/alerts">> = Specific
  const handler = {} as typeof import("../../../src/app/api/dashboard/admin/alerts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/dashboard/admin/approvals/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/admin/approvals">> = Specific
  const handler = {} as typeof import("../../../src/app/api/dashboard/admin/approvals/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/dashboard/admin/commission/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/admin/commission">> = Specific
  const handler = {} as typeof import("../../../src/app/api/dashboard/admin/commission/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/dashboard/admin/escrow/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/admin/escrow">> = Specific
  const handler = {} as typeof import("../../../src/app/api/dashboard/admin/escrow/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/dashboard/admin/financials/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/admin/financials">> = Specific
  const handler = {} as typeof import("../../../src/app/api/dashboard/admin/financials/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/dashboard/admin/overview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/admin/overview">> = Specific
  const handler = {} as typeof import("../../../src/app/api/dashboard/admin/overview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/dashboard/admin/payouts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/admin/payouts">> = Specific
  const handler = {} as typeof import("../../../src/app/api/dashboard/admin/payouts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/dashboard/admin/reports/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/admin/reports">> = Specific
  const handler = {} as typeof import("../../../src/app/api/dashboard/admin/reports/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/dashboard/admin/reviews/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/admin/reviews">> = Specific
  const handler = {} as typeof import("../../../src/app/api/dashboard/admin/reviews/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/dashboard/admin/sessions/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/admin/sessions/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/dashboard/admin/sessions/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/dashboard/admin/sessions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/admin/sessions">> = Specific
  const handler = {} as typeof import("../../../src/app/api/dashboard/admin/sessions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/dashboard/admin/teacher-pricing/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/admin/teacher-pricing">> = Specific
  const handler = {} as typeof import("../../../src/app/api/dashboard/admin/teacher-pricing/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/dashboard/admin/transactions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/admin/transactions">> = Specific
  const handler = {} as typeof import("../../../src/app/api/dashboard/admin/transactions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/dashboard/admin/trials/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/admin/trials">> = Specific
  const handler = {} as typeof import("../../../src/app/api/dashboard/admin/trials/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/dashboard/admin/users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/admin/users">> = Specific
  const handler = {} as typeof import("../../../src/app/api/dashboard/admin/users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/dashboard/parent/alerts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/parent/alerts">> = Specific
  const handler = {} as typeof import("../../../src/app/api/dashboard/parent/alerts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/dashboard/parent/calendar/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/parent/calendar">> = Specific
  const handler = {} as typeof import("../../../src/app/api/dashboard/parent/calendar/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/dashboard/parent/gamification/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/parent/gamification">> = Specific
  const handler = {} as typeof import("../../../src/app/api/dashboard/parent/gamification/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/dashboard/parent/homework/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/parent/homework">> = Specific
  const handler = {} as typeof import("../../../src/app/api/dashboard/parent/homework/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/dashboard/parent/leaderboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/parent/leaderboard">> = Specific
  const handler = {} as typeof import("../../../src/app/api/dashboard/parent/leaderboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/dashboard/parent/overview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/parent/overview">> = Specific
  const handler = {} as typeof import("../../../src/app/api/dashboard/parent/overview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/dashboard/parent/payments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/parent/payments">> = Specific
  const handler = {} as typeof import("../../../src/app/api/dashboard/parent/payments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/dashboard/parent/refunds/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/parent/refunds">> = Specific
  const handler = {} as typeof import("../../../src/app/api/dashboard/parent/refunds/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/dashboard/parent/reports/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/parent/reports">> = Specific
  const handler = {} as typeof import("../../../src/app/api/dashboard/parent/reports/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/dashboard/parent/sessions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/parent/sessions">> = Specific
  const handler = {} as typeof import("../../../src/app/api/dashboard/parent/sessions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/dashboard/parent/students/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/parent/students">> = Specific
  const handler = {} as typeof import("../../../src/app/api/dashboard/parent/students/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/dashboard/parent/trials/available-slots/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/parent/trials/available-slots">> = Specific
  const handler = {} as typeof import("../../../src/app/api/dashboard/parent/trials/available-slots/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/dashboard/parent/trials/book/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/parent/trials/book">> = Specific
  const handler = {} as typeof import("../../../src/app/api/dashboard/parent/trials/book/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/dashboard/teacher/complete-session/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/teacher/complete-session">> = Specific
  const handler = {} as typeof import("../../../src/app/api/dashboard/teacher/complete-session/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/dashboard/teacher/courses/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/teacher/courses">> = Specific
  const handler = {} as typeof import("../../../src/app/api/dashboard/teacher/courses/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/dashboard/teacher/homework/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/teacher/homework">> = Specific
  const handler = {} as typeof import("../../../src/app/api/dashboard/teacher/homework/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/dashboard/teacher/overview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/teacher/overview">> = Specific
  const handler = {} as typeof import("../../../src/app/api/dashboard/teacher/overview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/dashboard/teacher/payouts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/teacher/payouts">> = Specific
  const handler = {} as typeof import("../../../src/app/api/dashboard/teacher/payouts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/dashboard/teacher/profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/teacher/profile">> = Specific
  const handler = {} as typeof import("../../../src/app/api/dashboard/teacher/profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/dashboard/teacher/reviews/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/teacher/reviews">> = Specific
  const handler = {} as typeof import("../../../src/app/api/dashboard/teacher/reviews/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/dashboard/teacher/schedule/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/teacher/schedule">> = Specific
  const handler = {} as typeof import("../../../src/app/api/dashboard/teacher/schedule/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/dashboard/teacher/students/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/teacher/students">> = Specific
  const handler = {} as typeof import("../../../src/app/api/dashboard/teacher/students/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/dashboard/teacher/wallets/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/teacher/wallets">> = Specific
  const handler = {} as typeof import("../../../src/app/api/dashboard/teacher/wallets/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/gamification/equip/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/gamification/equip">> = Specific
  const handler = {} as typeof import("../../../src/app/api/gamification/equip/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/gamification/mystery-box/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/gamification/mystery-box">> = Specific
  const handler = {} as typeof import("../../../src/app/api/gamification/mystery-box/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/media/file/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/media/file">> = Specific
  const handler = {} as typeof import("../../../src/app/api/media/file/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/media/token/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/media/token">> = Specific
  const handler = {} as typeof import("../../../src/app/api/media/token/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/notifications/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications">> = Specific
  const handler = {} as typeof import("../../../src/app/api/notifications/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/payment/checkout/details/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payment/checkout/details">> = Specific
  const handler = {} as typeof import("../../../src/app/api/payment/checkout/details/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/payment/checkout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payment/checkout">> = Specific
  const handler = {} as typeof import("../../../src/app/api/payment/checkout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/payment/sandbox-confirm/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payment/sandbox-confirm">> = Specific
  const handler = {} as typeof import("../../../src/app/api/payment/sandbox-confirm/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/payment/webhooks/paymob/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payment/webhooks/paymob">> = Specific
  const handler = {} as typeof import("../../../src/app/api/payment/webhooks/paymob/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/payment/webhooks/stripe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/payment/webhooks/stripe">> = Specific
  const handler = {} as typeof import("../../../src/app/api/payment/webhooks/stripe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/recommendations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/recommendations">> = Specific
  const handler = {} as typeof import("../../../src/app/api/recommendations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/reports/send-weekly/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reports/send-weekly">> = Specific
  const handler = {} as typeof import("../../../src/app/api/reports/send-weekly/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/reviews/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reviews">> = Specific
  const handler = {} as typeof import("../../../src/app/api/reviews/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api">> = Specific
  const handler = {} as typeof import("../../../src/app/api/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/site/gallery/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/site/gallery">> = Specific
  const handler = {} as typeof import("../../../src/app/api/site/gallery/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/site/home/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/site/home">> = Specific
  const handler = {} as typeof import("../../../src/app/api/site/home/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/site/settings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/site/settings">> = Specific
  const handler = {} as typeof import("../../../src/app/api/site/settings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/site/slider/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/site/slider">> = Specific
  const handler = {} as typeof import("../../../src/app/api/site/slider/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/site/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/site/stats">> = Specific
  const handler = {} as typeof import("../../../src/app/api/site/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/site/teachers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/site/teachers">> = Specific
  const handler = {} as typeof import("../../../src/app/api/site/teachers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/site/testimonials/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/site/testimonials">> = Specific
  const handler = {} as typeof import("../../../src/app/api/site/testimonials/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/supervisor/payout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/supervisor/payout">> = Specific
  const handler = {} as typeof import("../../../src/app/api/supervisor/payout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/supervisor/report/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/supervisor/report/[id]">> = Specific
  const handler = {} as typeof import("../../../src/app/api/supervisor/report/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/supervisor/report/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/supervisor/report">> = Specific
  const handler = {} as typeof import("../../../src/app/api/supervisor/report/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/tracks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tracks">> = Specific
  const handler = {} as typeof import("../../../src/app/api/tracks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../src/app/api/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/upload">> = Specific
  const handler = {} as typeof import("../../../src/app/api/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
